// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/jmccarty3/awsScaler/api/remediation/remediators/aws (interfaces: AutoscalingClient)

package aws

import (
	autoscaling "github.com/aws/aws-sdk-go/service/autoscaling"
	gomock "github.com/golang/mock/gomock"
)

// Mock of AutoscalingClient interface
type MockAutoscalingClient struct {
	ctrl     *gomock.Controller
	recorder *_MockAutoscalingClientRecorder
}

// Recorder for MockAutoscalingClient (not exported)
type _MockAutoscalingClientRecorder struct {
	mock *MockAutoscalingClient
}

func NewMockAutoscalingClient(ctrl *gomock.Controller) *MockAutoscalingClient {
	mock := &MockAutoscalingClient{ctrl: ctrl}
	mock.recorder = &_MockAutoscalingClientRecorder{mock}
	return mock
}

func (_m *MockAutoscalingClient) EXPECT() *_MockAutoscalingClientRecorder {
	return _m.recorder
}

func (_m *MockAutoscalingClient) DescribeAutoScalingGroups(_param0 *autoscaling.DescribeAutoScalingGroupsInput) (*autoscaling.DescribeAutoScalingGroupsOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribeAutoScalingGroups", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribeAutoScalingGroupsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoscalingClientRecorder) DescribeAutoScalingGroups(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeAutoScalingGroups", arg0)
}

func (_m *MockAutoscalingClient) DescribeAutoScalingInstances(_param0 *autoscaling.DescribeAutoScalingInstancesInput) (*autoscaling.DescribeAutoScalingInstancesOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribeAutoScalingInstances", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribeAutoScalingInstancesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoscalingClientRecorder) DescribeAutoScalingInstances(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeAutoScalingInstances", arg0)
}

func (_m *MockAutoscalingClient) DescribeLaunchConfigurations(_param0 *autoscaling.DescribeLaunchConfigurationsInput) (*autoscaling.DescribeLaunchConfigurationsOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribeLaunchConfigurations", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribeLaunchConfigurationsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoscalingClientRecorder) DescribeLaunchConfigurations(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeLaunchConfigurations", arg0)
}

func (_m *MockAutoscalingClient) DescribeScalingActivities(_param0 *autoscaling.DescribeScalingActivitiesInput) (*autoscaling.DescribeScalingActivitiesOutput, error) {
	ret := _m.ctrl.Call(_m, "DescribeScalingActivities", _param0)
	ret0, _ := ret[0].(*autoscaling.DescribeScalingActivitiesOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoscalingClientRecorder) DescribeScalingActivities(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DescribeScalingActivities", arg0)
}

func (_m *MockAutoscalingClient) SetDesiredCapacity(_param0 *autoscaling.SetDesiredCapacityInput) (*autoscaling.SetDesiredCapacityOutput, error) {
	ret := _m.ctrl.Call(_m, "SetDesiredCapacity", _param0)
	ret0, _ := ret[0].(*autoscaling.SetDesiredCapacityOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockAutoscalingClientRecorder) SetDesiredCapacity(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "SetDesiredCapacity", arg0)
}
